version: '3'

services:
  playwright:
    image: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    environment:
      - CI=true
      - BASE_URL=${BASE_URL:-https://opensource-demo.orangehrmlive.com}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: npm run test:smoke